[versions]
# Minecraft
minecraft-version = "1.21.8"
minecraft-required = ">=1.21.8"
minecraft-fabric-compatible = "1.21.8"

yarn = "1.21.8+build.1"

# Fabric
fabric-loader = "0.18.+"
fabric-api = "0.136.1+1.21.8"

# Forge
forge-loader = "1.21.1-52.1.0"

# Neoforged
neoforge-loader = "21.1.121"

# Mods
accessories = "1.3.8-beta+1.21.8"
curios = "5.9.1+1.20.1"
emi = "1.1.10+1.21"

# Libraries
annotations = "23.+"
mixin = "0.15.0+mixin.0.8.7"

testng = "7.5.1"

# Plugins
loom = "1.+"
minotaur = "2.+"

[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft-version" }
yarn = { module = "net.fabricmc:yarn", version.ref = "yarn" }

fabric-loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric-loader" }
fabric-api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric-api" }

accessories = { module = "io.wispforest:accessories-fabric", version.ref = "accessories" }

emi = { module = "dev.emi:emi-xplat-intermediary", version.ref = "emi" }
emi-fabric = { module = "dev.emi:emi-fabric", version.ref = "emi" }

annotations = { module = "org.jetbrains:annotations", version.ref = "annotations" }
mixin = { module = "net.fabricmc:sponge-mixin", version.ref = "mixin" }

testng = { module = "org.testng:testng", version.ref = "testng" }

[bundles]
fabric = ["fabric-loader", "fabric-api", "accessories"]

fabric-runtime = ["emi-fabric"]

compile-only = ["annotations"]

[plugins]
loom = { id = "dev.architectury.loom", version.ref = "loom" }
minotaur = { id = "com.modrinth.minotaur", version.ref = "minotaur" }
